package lk.sliit.railconnect.features.booking.service;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import lk.sliit.railconnect.features.booking.domain.BookingSeat;
import lk.sliit.railconnect.features.booking.domain.Payment;
import lk.sliit.railconnect.features.booking.domain.TicketBooking;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.util.List;

@Service
public class BookingPdfService {
    private final BookingService bookingService;

    public BookingPdfService(BookingService bookingService) {
        this.bookingService = bookingService;
    }

    public byte[] createTicket(TicketBooking booking) {
        try {
            ByteArrayOutputStream output = new ByteArrayOutputStream();
            Document document = new Document(PageSize.A5, 36, 36, 36, 36);
            PdfWriter.getInstance(document, output);
            document.open();

            Font title = new Font(Font.HELVETICA, 20, Font.BOLD, new Color(7, 43, 82));
            Font heading = new Font(Font.HELVETICA, 12, Font.BOLD, new Color(7, 43, 82));
            document.add(new Paragraph("RailConnect", title));
            document.add(new Paragraph("E-ticket | " + booking.getBookingReference(), heading));
            document.add(new Paragraph(" "));

            PdfPTable details = new PdfPTable(new float[]{1.1f, 2.3f});
            details.setWidthPercentage(100);
            addRow(details, "Passenger", booking.getPassengerName());
            addRow(details, "Train", booking.getSchedule().getTrain().getTrainName() + " (" + booking.getSchedule().getTrain().getTrainNumber() + ")");
            addRow(details, "Journey", booking.getSchedule().getRoute().getStartStation() + " - " + booking.getSchedule().getRoute().getEndStation());
            addRow(details, "Travel", booking.getSchedule().getTravelDate() + " at " + booking.getSchedule().getDepartureTime());
            addRow(details, "Seats", seats(bookingService.seatsForBooking(booking.getId())));
            addRow(details, "Total", "LKR " + booking.getTotalAmount());
            List<Payment> payments = bookingService.paymentsForBooking(booking.getId());
            if (!payments.isEmpty()) {
                Payment payment = payments.get(payments.size() - 1);
                addRow(details, "Payment", payment.getMethod().name().replace('_', ' ') + " - " + payment.getStatus());
            }
            document.add(details);
            document.add(new Paragraph(" "));
            Paragraph note = new Paragraph("Please carry a valid identity document. This ticket was generated by the RailConnect booking system.",
                    new Font(Font.HELVETICA, 9, Font.NORMAL, Color.DARK_GRAY));
            note.setAlignment(Element.ALIGN_LEFT);
            document.add(note);
            document.close();
            return output.toByteArray();
        } catch (DocumentException exception) {
            throw new IllegalStateException("Ticket PDF could not be generated.", exception);
        }
    }

    private void addRow(PdfPTable table, String label, String value) {
        PdfPCell labelCell = new PdfPCell(new Phrase(label, new Font(Font.HELVETICA, 10, Font.BOLD)));
        labelCell.setBackgroundColor(new Color(235, 242, 250));
        labelCell.setPadding(7);
        PdfPCell valueCell = new PdfPCell(new Phrase(value, new Font(Font.HELVETICA, 10)));
        valueCell.setPadding(7);
        table.addCell(labelCell);
        table.addCell(valueCell);
    }

    private String seats(List<BookingSeat> seats) {
        return seats.stream()
                .map(item -> item.getSeat().getCarriage().getCarriageNumber() + "-" + item.getSeat().getSeatNumber())
                .reduce((left, right) -> left + ", " + right)
                .orElse("None");
    }
}
